version: "3"
services:
  mongo-express:
    image: mongo-express
    container_name: kuwana.mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: totvs.123
      ME_CONFIG_MONGODB_PORT: 27017
    links:
      - mongo
    networks:
      - mongo-network

  mongo:
    image: mongo
    container_name: kuwana.mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mongo-network

networks: 
    mongo-network:
      driver: bridge

volumes:
  mongo_data:
    external: true
